<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>WorkData</AssemblyName>
    <ApplicationTitle>WorkData</ApplicationTitle>
  </PropertyGroup>

  <ItemGroup>
        <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
        <PackageReference Include="NPOI" Version="2.6.2" />
    </ItemGroup>

  <ItemGroup>
    <Content Include="app.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>